### ISSUE TITLE
[feature] [optimization] Cancel previous in-flight async validation http requests using cancellationTokens

### ISSUE THREAD

**Issue by benmccallum** [jeffhandley/strickland#21]
Not sure if this is possible, just throwing it out there, but it'd be cool to be able to (for performance and race-condition handling) to have async validations that use HTTP requests cancel any current/previous in-flight requests. 

Since we wouldn't want to lock anyone into a particular way of making their HTTP requests, we'd need them to provide a way to instruct Strickland on how cancel the request (similarly to how the automatic race condition handling works by the user providing a func to grab the latest value for comparison).

This might be able to be extended out more generally to not just HTTP requests but the entire async validator's Promise, I'd need to look at the API for that. i.e. we let them pass in a "deconstructor" func, on new async validation fired we check for previous non-completed Promises, and for each, close them and call their deconstructor func.

**Comment by jeffhandley** [comment]
This is a great idea.  I like your deconstructor function idea too.  Just spit-balling:

``` jsx
export default function validate() {
    let asyncToken;
    let asyncCanceled;

    return {
        validateAsync() {
            if (!asyncCanceled) {
                asyncToken = window.setTimeout(...);
            }
        },
        cancelAsync() {
            if (asyncToken) {
                window.clearTimeout(asyncToken);
            }
        }
    };
}
````

This would essentially just define a pattern that a `cancelAsync` function on a validation result will cancel any pending async validation, even before it begins. The `all`, `every`, `some`, and `objectProps` validators could expose their own `cancelAsync` functions that iterate over the validators looking for `cancelAsync` functions and invoking them, applying the same pattern themselves.

Is this kind of pattern in line with what you were thinking?

**Comment by benmccallum** [comment]
Sounds good to me! Sorry in advance, I'm just about to jump on a plane and may not get much time this week but I'll see how things go. I'd be keen to see that pattern implemented and then contribute an axios example in the demos. I'm sure we can find a free API to hit.

**Comment by jeffhandley** [comment]
No worries.  I'd be happy to implement this.

I'm wondering if there's a way to represent the pattern when a validator returns a function for async instead of returning an initial result with `validateAsync()` defined.

``` jsx
function validate() {
    let asyncToken;
    let asyncCancel;

    function validateAsync() {
        if (!asyncCancel) {
            asyncToken = window.setTimeout(...);
        }
    }

    validateAsync.cancelAsync = function cancelAsync() {
        asyncCancel = true;

        if (asyncToken) {
            window.clearTimeout(asyncToken);
        }
    }

    return validateAsync;
}
```

Doing this, when strickland identifies that a validator returns a function to:

1. Create an initial result and wire up the `validateAsync` function on it
2. Check the function to see if it contains a property for `cancelAsync` and if so, wire that up too

But I also want to think about how Promise-based results would work. Have you seen a good pattern for canceling promises?

**Comment by benmccallum** [comment]
```js
import validate from 'strickland';

function usernameIsAvailable(username, token) {
    return new Promise((resolve) => {
        // Setup cancellation on token
        token.cancel = function (reason) {
            // Cancel "things" like in-flight network requests, computation, etc.
            // ...

            //
            reject(reason);
        }

        if (username === 'marty') {
            // Resolve to an invalid validation result object
            resolve({
                isValid: false,
                message: `"${username}" is not available`
            });
        }

        // Resolve to a boolean
        resolve(true);
    });
}

let token = { };
const result = validate(usernameIsAvailable, 'marty', token);

result.validateAsync().then(...);

token.cancel();
```

**Comment by benmccallum** [comment]
Scribbled some stuff above, gotta head off though. Hopefully some of that makes sense to you. I think the basic premise is to pass around a token and have the implementation of the Promise setup the cancellation function on that token to be called by whoever, whenever. 

I guess the token would need to be passed around in Strickland internals, but all the way out as well so that the validation result managed in react/vue state provides access to all the cancellationTokens to be used by the UI, say in a route change or deconstruction of a component, to cancel any current long-running validations. That'd be a pretty intense optimization but could be useful and it wouldn't be hard to pass the token out with isValid, other props, etc.

**Comment by jeffhandley** [comment]
Closing this as stale. We landed where previous async validation responses can easily be ignored and a consumer should be able to implement cancelation themselves using whatever async calling library they are using.

**Comment by benmccallum** [comment]
No worries. 👍
