### ISSUE TITLE
Throttle validation firing on <select> when navigated with arrow keys.

### ISSUE THREAD

**Issue by benmccallum** [jeffhandley/strickland#24]
I noticed when building the Vue demo, that if you navigate a `<select>` with the arrow keys, it'll fire off the validation (off the back of `input` or `change` event, can't exactly remember) as you're changing options. For basic validation that's probably not an issue, but for async/complex validation this could cause problems if the user is navigating quickly up/down a list trying to find their desired option. 

Potentially we can implement some kind of basic delay or throttling, but the more I think of it this isn't a Strickland framework concern but more of a UI/integration with Strickland concern. So something the React and Vue demos should handle. 

Maybe we don't care so much? I don't want to overcomplicate the react demo. Potentially I look at addressing this in the vue-strickland plugin.

**Comment by jeffhandley** [comment]
Closing as stale.

**Comment by benmccallum** [comment]
No worries. I've been pretty busy and haven't been able to get back to my passion project using Strickland so when I do get back I'll see how all this goes 👍
