### ISSUE TITLE
Investigate react hooks

### ISSUE THREAD

**Issue by benmccallum** [jeffhandley/strickland#25]
Random thought, I wonder what react hooks (and indeed Vue's hooks when they land) could do for the strickland <> form integration/hook up.

I know for the vue demo I use a `mixin` which is like inheritance but mixins have a number of problems as your app gets larger. So hooks would definitely help with the bootstrapping of a form with strickland.

**Comment by maraisr** [comment]
In what way, are you thinking of something like this?

```ts
import React, { FunctionComponent, useState, useEffect } from 'react';
import validate, { all, min, required } from 'strickland';

const shareableValidationChain = all([
		required(),
		min({ minLength: 10 }),
	]);

const MySomething: FunctionComponent = () => {
	const [ value, setValue ] = useState('');

	const { isValid, message } = useValidator(shareableValidationChain, value);

	return (<>
		<input value={value} onChange={e => setValue(e.currentTarget.value)}/>
		{!isValid && <p>{message}</p>}
	</>);
};

function useValidator(rules, value) {
	const [ result, setResult ] = useState();

	useEffect(() => {
		setResult(validate(rules, value));
	}, [ value ]);

	return result;
}
```
> this would be got a `validate on change` kinda scenario.

for a `validate on submit`, calling validate directly would still work maybe?

_this was just a quick play, i'll clone later tonight and see what happens.._

**Comment by benmccallum** [comment]
Honestly haven't had time to fully get across hooks. I understand the concept but don't know the finer details around which hooks like useState and useEffect would need to be leveraged.

So I could be wrong, it's been a while since I looked at the demos, but was just thinking that the wiring as per the react example in here and the one I did for Vue could stand to gain from hooks if it makes it nicer to wire up to your form.

So to answer your question, I hadn't really thought it through, was just a brain dump Todo :p

**Comment by maraisr** [comment]
Would be cool to see how this plays in a "the form is valid" kinda context, ie, maybe some way to aggregate the validation states from all the "per fields" or something.

Might be worth checking out how `formik` wants you to handle validation. Might be a good place to start.

Right now we shape what the payload needs to look like for a final "submit", then add the validation thingos to that using yup. Then you build your form how you please and the wiring kinda flows in quite nicely, you hook up the `message` to the hintText prop of the input, and bobs your uncle.
