### ISSUE TITLE
Need a way to validate an array of objects

### ISSUE THREAD

**Issue by jeffhandley** [jeffhandley/strickland#36]
Sparked from this tweet by @CrshOverride: https://twitter.com/CrshOverride/status/1278011103465914369?s=20

The `objectProps` validator and the [convention](https://www.strickland.io/composition/conventions) for validating objects make validating objects easy.  But many data structures include arrays of objects, and there's no built-in validator that assists with validating arrays of objects.

The following data snippet illustrates a very simple and common scenario:

``` js
{
  name: 'Justin',
  phones: [{
    areaCode: '555',
    number: '5555555'
  }]
}
```

Validation of this array can be done, but it requires a custom validator to be built for validating the array.  [This Gist](https://gist.github.com/jeffhandley/dee69c7318aa603b4d194a6bc45a980f) illustrates how it can be done, with code like this:

``` js
var phoneValidator = {
    areaCode: length(3, 3),
    number: length(8, 8)
};

function phonesValidator(phones, context) {
    if (phones && !Array.isArray(phones)) {
        return false;
    }

    var isValid = true;
    var validationResults = phones.map((phone) => {
        var result = validate(phoneValidator, phone, context);
        isValid = isValid && result.isValid;

        return result;
    });

    return {
        isValid,
        validationResults,
        ...(isValid ? {} : { message: 'At least one phone number is invalid' })
    };
}

var validator = {
    name: required({message: 'name is required'}),
    phones: [
        minLength(1, { message: 'You must specify at least one phone number' }),
        phonesValidator
    ]
};
```

There should be a built-in validator that can validate an array of objects, and there should likely be a convention to make this as straightforward as object validation.  This validator will need to provide a shape of results that matches the array that is validated.

**Note:**
For better or worse, the convention of a validator being an array is already used to indicate that an _array of validators_ need to be validated (with the `every` validator)--it's much more common to need to achieve that than it is to validate an array of objects, so that'll be OK.

**Comment by jeffhandley** [comment]
Here's a proposal for an `arrayOf` validator. The example below illustrates how an array can be validated to be required, with a minimum array length, and with each element having its own validators. In this case, each element is required and must pass object validation.

The `arrayOf` validator could also be used to validate arrays of scalars; it is not required that the arrays are composed of objects to be validated with the `objectProps` validator (or its convention). 

``` js
var data = {
    name: 'Justin',
    phones: [{
        areaCode: '555',
        number: '5555555'
    }]
}

var validator = {
    name: required(),
    phones: [required(), minLength(1), arrayOf([
        required(), {
            areaCode: [required(), length(3, 3)],
            number: [required(), length(7, 7)]
        }
    ])]
}

var result = validate(validator, data);
```

The validation result that would get produced for this scenario would be:

``` js
{
    isValid: true,
    objectProps: {
        name: {
            isValid: true,
            required: true,
            value: 'Justin'
        },
        phones: {
            isValid: true,
            required: true,
            minLength(1),
            arrayOf: [
                {
                    isValid: true,
                    required: true,
                    objectProps: {
                        areaCode: {
                            isValid: true,
                            required: true,
                            minLength: 3,
                            maxLength: 3,
                            value: '555'
                        },
                        number: {
                            isValid: true,
                            required: true,
                            minLength(7),
                            maxLength(7),
                            value: '5555555'
                        }
                    },
                    every: [ /* suppressed for illustration, but would contain the required and objectProps validator results */ ],
                    value: {
                        areaCode: '555',
                        number: '5555555'
                    }
                }
            ],
            every: [ /* suppressed for illustration, but would contain the required, minLength, and arrayOf validator results */ ],
            value: [
                {
                    areaCode: '555',
                    number: '5555555'
                }
            ]
        }
    },
    value: {
        name: 'Justin',
        phones: [
            {
                areaCode: '555',
                number: '5555555'
            }
        ]
    }
}
```

**Comment by jeffhandley** [comment]
I cannot think of a good convention to use for `arrayOf`. I had a moment of regret that the array convention was used to imply the `every` validator should be used, but I'm over that -- it's much more common to want to provide an array of validators than it is to validate a value that itself is an array.

**Comment by jeffhandley** [comment]
@CrshOverride What do you think of[ this proposal](https://github.com/jeffhandley/strickland/issues/36#issuecomment-653683920) for validating an array?

**Comment by CrshOverride** [comment]
@jeffhandley Looks great! It, conceptually, winds up being very similar to what my array validation builds now but the shape of the output is much nicer.

**Comment by jeffhandley** [comment]
Thanks, @CrshOverride. The only thing I'm pausing on is the name. I want to make sure the name unambiguously denotes that the function accepts a validator that will be applied to all array elements. And I want the name to be consistent with how `objectProps` is named.

Rather than `arrayOf`, I'm leaning toward `arrayElements`.  I feel like that validation result shape would be even more clear with that too, with an `arrayElements` result prop that is an array matching the shape of the array that was validated.

I'm going to make that change and then get this merged in.
